
CREATE DATABASE USERMANAGEMENT
GO
USE USERMANAGEMENT
GO
CREATE TABLE GROUPS(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION NVARCHAR(MAX),
	ACTIVE BIT NOT NULL DEFAULT 0,
	REGISTRATIONDATE DATETIME NOT NULL
)
GO
CREATE TABLE PERSON(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CPF CHAR(11) NOT NULL,
	EMAIL VARCHAR(120) NOT NULL,
	DDD CHAR(2) NOT NULL,
	NUMBER CHAR(9) NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 0,
	REGISTRATIONDATE DATETIME NOT NULL
)
GO
CREATE TABLE USERS(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	USERLOGIN VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	DAYSRENEWAL INT NOT NULL,
	IDPERSON INT NOT NULL,
	IDGROUP INT NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 0,
	REGISTRATIONDATE DATETIME NOT NULL,

	FOREIGN KEY (IDPERSON) REFERENCES PERSON(ID),
	FOREIGN KEY (IDGROUP) REFERENCES GROUPS(ID)
)
GO 
CREATE TABLE GETUSERGROUP(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	IDUSER INT NOT NULL,
	IDGROUP INT NOT NULL,
)